- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: inatall the  nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

