- name: datatypes         #datatypes 
  hosts: localhost
  vars: 
    Courses: Devops with AWS
    Tools:  #lists
    - Ansible
    - Jenkins
    - Git
    - Docker
    - Kubernetes
    Experience:    #Dictionaries or mapping
      docker: 3
      kubernetes: 2
      jenkins: 1
      git: 1
      ansible: 1
    RealProject: true    #boolean
  tasks: 
    - name: print the variables
      ansible.builtin.debug:
        msg: "I learning the courses of {{ Courses }} with the tools of {{Tools}} and has a experiences of {{Experience}} is a real project {{RealProject}} "
  
    

