- name: the conditions
  hosts: web 
  become: true
  tasks:
  - name: check the user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true
  - name: create user
    ansible.builtin.debug:
      msg: "User Info : {{USER}}"

  - name: create a user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
  - name: hello
    ansible.builtin.debug: 
      msg: " hello"
