- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "{{coure | default('Ansible')}}"
- name: uppercase
  hosts: localhost
  tasks:
- name: print uppercase 
  hosts: localhost
  vars:
    greeting: " hello , Good Morning"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper}}"

- name: print lowercase 
  hosts: localhost
  vars:
    greeting: " hello , Good Morning"
  tasks:
  - name: convert into the lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove the Duplicates
  hosts: localhost
  vars: 
  - numbers: [1,2,3,2,3,4,5,5,5,7,8]
  tasks:
  - name: remove the Duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique}}"

- name: get the min and max values
  hosts: localhost
  vars: 
  - age: [23,45,62,71,56,34,33,98]
  tasks:
  - name:  print the min and max values
    ansible.builtin.debug:
      msg: " min age: {{ age | min}} and max age: {{ age | max}}"
- name: Convert Dictionaries to lists
  hosts: localhost
  vars:
  - my_dict:
      Course : Ansible
      Trainer: sivakumar
      Duration : 120hr
  tasks:
  - name: before converting
    ansible.builtin.debug:
      msg: "Before convert: {{my_dict}}"
  - name: After converting
    ansible.builtin.debug:
      msg: " after conversion: {{my_dict | dict2items}}"

- name: convert list into Dictionaries
  hosts: localhost
  vars:
  - my_list:
      - {'key': 'Course', 'value': 'Ansible'}
      - {'key': 'Trainer', 'value': 'sivakumar'}
      - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before converting
    ansible.builtin.debug:
      msg: "Before convert: {{my_list}}"
  - name: After converting
    ansible.builtin.debug:
      msg: " after conversion: {{my_list | items2dict}}"
