- name: Install the Packages
  hosts: localhost
  become: true
  tasks:
  - name: inatall the Packages
    ansible.builtin.dnf:
      name: " install {{items}}"
      state: latest
    loop:
    - nginx
    - git
    - mysql

  