- name: Install the Packages
  hosts: web
  become: yes
  tasks:
  - name: inatall the Packages
    ansible.builtin.dnf:
      name: "{{ items }}"
      state: latest
    loop:
    - nginx
    - git
    - mysql

  