- name: Variables from the Prompts
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter the USERNAME
    private: false
  - name: PASSWORD
    prompt: Please enter the PASSWORD
    private: true
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "USERNAME: {{ USERNAME }} PASSWORD: {{ PASSWORD }}"   
